version: '3'
services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    command: pipenv run server
    volumes:
      - .:/app
    ports:
      - 7000:7000
    depends_on:
      - db
volumes:
  postgresql:
